### ISSUE TITLE
Issue after about 7h

### ISSUE THREAD

**Issue by flozo98** [miykael/3dprintyourbrain#11]
Hello,
i managed to set up freesurfer and the other tools as explained (at least I think so) but after i started the "recon-all" command from step two after roughly seven hours it stops. 
I tried it twice on two different machines and both times the last lines in the terminal are nearly the same.
"Waiting for PID 17875 of (17875 17878) to complete..."
and
"Waiting for PID 17873 of (11573 11576) to complete..."
I ran it for at least 10 hours longer but nothing happened.
Can you please help me figure out what the problem is?

Update!:
Another try with the T1+KM stoped at 
"Waiting for PID 24258 of (24258 24261) to complete..."

![Bildschirmfoto von 2019-12-27 10-58-36](https://user-images.githubusercontent.com/59280826/71512782-f5f70200-2897-11ea-907b-c7ead5cd3cc4.png)

**Comment by jonathanlundstrom** [comment]
Hey!

I too have this problem. Got hold of a T1 MRI from a friend of mine but it's been stuck at these lines now for about 8h. Did you figure out how to resolve this?

```
#@# Fix Topology rh Sun Mar 22 11:34:05 CET 2020
\n mris_fix_topology -rusage /Users/jonathan/Documents/brain/jonas/output/touch/rusage.mris_fix_topology.rh.dat -mgz -sphere qsphere.nofix -ga -seed 1234 output rh \n
Waiting for PID 29558 of (29558 29561) to complete...
```

Thanks!

**Comment by miykael** [comment]
Hello guys. Sorry @flozo98 for not answering to your previous message.

Both of these issues are particular to FreeSurfer's `recon-all` algorithm, I would therefore recommend you to look into their mailing list or ask your question there.

But the step where it seems to be stuck is the fixing of the surface topology, i.e. correcting errors and uncertainties during the cortical surface reconstruction. In my experience, this often happens when the surface reconstruction was already very bad to begin with. This can either be due to a very noisy or faulty T1 image or some other things. Again, from my side (or the code that this repository offers here), there's nothing that can be done. This depends much more on FreeSurfer's recon-all command.

Good luck,
Michael
